// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWs-MKB7ncrsRMCy0Sb9pQ_Pu-IgzuYT0',
    appId: '1:504983584526:web:42e24550be2383dbf7615f',
    messagingSenderId: '504983584526',
    projectId: 'mama-bus-koi-4535e',
    authDomain: 'mama-bus-koi-4535e.firebaseapp.com',
    storageBucket: 'mama-bus-koi-4535e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfPl_tUmjcOjzScoEESCMJZdBrL01ZpQQ',
    appId: '1:504983584526:android:5adc9200a8ad7452f7615f',
    messagingSenderId: '504983584526',
    projectId: 'mama-bus-koi-4535e',
    storageBucket: 'mama-bus-koi-4535e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLm5KpRjR6K0UsWdmhNn-Rx7Att2cco1g',
    appId: '1:504983584526:ios:59177ea4c425f41ef7615f',
    messagingSenderId: '504983584526',
    projectId: 'mama-bus-koi-4535e',
    storageBucket: 'mama-bus-koi-4535e.firebasestorage.app',
    iosBundleId: 'com.Codebaba.Ezaz.mamaBusKoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLm5KpRjR6K0UsWdmhNn-Rx7Att2cco1g',
    appId: '1:504983584526:ios:59177ea4c425f41ef7615f',
    messagingSenderId: '504983584526',
    projectId: 'mama-bus-koi-4535e',
    storageBucket: 'mama-bus-koi-4535e.firebasestorage.app',
    iosBundleId: 'com.Codebaba.Ezaz.mamaBusKoi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWs-MKB7ncrsRMCy0Sb9pQ_Pu-IgzuYT0',
    appId: '1:504983584526:web:a6fedae00104515af7615f',
    messagingSenderId: '504983584526',
    projectId: 'mama-bus-koi-4535e',
    authDomain: 'mama-bus-koi-4535e.firebaseapp.com',
    storageBucket: 'mama-bus-koi-4535e.firebasestorage.app',
  );
}
