// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Your Api Key . I have removed mine as it is a secret code',
    appId: 'Your Api Id . I have removed mine as it is a secret code',
    messagingSenderId: 'Your given sender ID . I have removed mine as it is a secret id',
    projectId: 'Your Project Id',
    authDomain: 'Your authDomain',
    storageBucket: 'Your Stoarge Bucket',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'Your Api Id . I have removed mine as it is a secret code',
    appId: 'Your Api Id . I have removed mine as it is a secret code',
    messagingSenderId: 'Your given sender ID . I have removed mine as it is a secret id',
    projectId: 'Your authDomain',
    storageBucket: 'Your Stoarge Bucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Your Api Key . I have removed mine as it is a secret code',
    appId: 'Your Api Id . I have removed mine as it is a secret code',
    messagingSenderId: 'Your given sender ID . I have removed mine as it is a secret id',
    projectId: 'Your Project Id',
    storageBucket: 'Your Stoarge Bucket',
    iosBundleId: 'com.Codebaba.Ezaz.mamaBusKoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'Your Api Key . I have removed mine as it is a secret code',
    appId: 'Your Api Id . I have removed mine as it is a secret code',
    messagingSenderId: 'Your given sender ID . I have removed mine as it is a secret id',
    projectId: 'Your Project Id',
    storageBucket: 'Your Stoarge Bucket',
    iosBundleId: 'com.Codebaba.Ezaz.mamaBusKoi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'Your Api Key . I have removed mine as it is a secret code',
    appId: 'Your Api Id . I have removed mine as it is a secret code',
    messagingSenderId: 'Your given sender ID . I have removed mine as it is a secret id',
    projectId: 'Your Project Id',
    authDomain: 'Your authDomain',
    storageBucket: 'Your Stoarge Bucket',
  );
}
